<?php

/**
 * @buief
 * @details AttributesMasterEntity.
 *
 * Generated By DaoGenerator.
 * 
 * @since 2015/02/13
 * @package Onota0318
 */
namespace Core\Model;

use Onota0318\Zend2Adapter\Model\AbstractEntity;

class AttributesMasterEntity extends AbstractEntity
{
    /**
     * @var varchar(255) not null
     */
    protected $key;

    /**
     * @var varchar(255) not null
     */
    protected $detail;

    /**
     * @var tinyint(1) 
     * @default 0
     * @column is_nullable
     * @castTo boolean
     */
    protected $isNullable;

    /**
     * @var tinyint(1) 
     * @default 1
     * @column is_secret
     * @castTo boolean
     */
    protected $isSecret;

    /**
     * @var datetime not null
     * @default 0000-00-00 00:00:00
     * @column deleted_date
     * @castTo datetime
     */
    protected $deletedDate;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column created_date
     * @castTo datetime
     */
    protected $createdDate;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column modified_date
     * @castTo datetime
     */
    protected $modifiedDate;

}