<?php
/**
 * @buief
 * @details AttributesMasterValidator.
 *
 * Generated By DaoGenerator.
 * 
 * TODO:※スケルトンです。適切に修正してください。
 *
 * @since 2015/02/13
 * @package Onota0318
 */
namespace Core\Model;
 
use Onota0318\Zend2Adapter\Model\AbstractValidator;

class AttributesMasterValidator extends AbstractValidator
{
    /**
     * validate for key 
     * 
     * @param mixed $input target value.
     * @param array $messages message list.
     * @return void
     */
    public function validateKey($input, array $messages = array())
    {
        $logical  = "属性名";
        $field     = "key";
        $nullable  = false;
        $minLength = 0;
        $maxLength = 255;

        $validator = array(
            "name"       => $field,
            "required"   => true,
            "validators" => array(
                $this->getNotEmptySignature($messages),
                $this->getStringLengthSignature($minLength, $maxLength, $messages),
                $this->getUnsupportedStringSignature($messages),
            ),
        );

        $this->verify($field, $input, $validator, $nullable, array($logical, $minLength, $maxLength));
    }

    /**
     * validate for detail 
     * 
     * @param mixed $input target value.
     * @param array $messages message list.
     * @return void
     */
    public function validateDetail($input, array $messages = array())
    {
        $logical  = "属性説明";
        $field     = "detail";
        $nullable  = false;
        $minLength = 0;
        $maxLength = 255;

        $validator = array(
            "name"       => $field,
            "required"   => true,
            "validators" => array(
                $this->getNotEmptySignature($messages),
                $this->getStringLengthSignature($minLength, $maxLength, $messages),
                $this->getUnsupportedStringSignature($messages),
            ),
        );

        $this->verify($field, $input, $validator, $nullable, array($logical, $minLength, $maxLength));
    }

    /**
     * validate for is_nullable 
     * 
     * @param mixed $input target value.
     * @param array $messages message list.
     * @return void
     */
    public function validateIsNullable($input, array $messages = array())
    {
        $logical  = "NULL許可フラグ";
        $field    = "is_nullable";
        $nullable = true;

        $validator = array(
            "name"       => $field,
            "required"   => true,
            "validators" => array(
                $this->getDigitsSignature($messages),
            ),
        );

        $this->verify($field, $input, $validator, $nullable, array($logical));
    }

    /**
     * validate for is_secret 
     * 
     * @param mixed $input target value.
     * @param array $messages message list.
     * @return void
     */
    public function validateIsSecret($input, array $messages = array())
    {
        $logical  = "機密情報フラグ";
        $field    = "is_secret";
        $nullable = true;

        $validator = array(
            "name"       => $field,
            "required"   => true,
            "validators" => array(
                $this->getDigitsSignature($messages),
            ),
        );

        $this->verify($field, $input, $validator, $nullable, array($logical));
    }

    /**
     * validate for deleted_date 
     * 
     * @param mixed $input target value.
     * @param array $messages message list.
     * @return void
     */
    public function validateDeletedDate($input, array $messages = array())
    {
    }

    /**
     * validate for created_date 
     * 
     * @param mixed $input target value.
     * @param array $messages message list.
     * @return void
     */
    public function validateCreatedDate($input, array $messages = array())
    {
    }

    /**
     * validate for modified_date 
     * 
     * @param mixed $input target value.
     * @param array $messages message list.
     * @return void
     */
    public function validateModifiedDate($input, array $messages = array())
    {
    }

}