<?php

/**
 * @buief
 * @details MemberEntity.
 *
 * Generated By DaoGenerator.
 * 
 * @since 2015/02/13
 * @package Onota0318
 */
namespace Core\Model;

use Onota0318\Zend2Adapter\Model\AbstractEntity;

class MemberEntity extends AbstractEntity
{
    /**
     * @var bigint(20) not null
     */
    protected $id;

    /**
     * @var varchar(255) not null
     * @column login_id
     */
    protected $loginId;

    /**
     * @var varchar(255) not null
     */
    protected $password;

    /**
     * @var varchar(255) not null
     * @column first_name
     */
    protected $firstName;

    /**
     * @var varchar(255) not null
     * @column last_name
     */
    protected $lastName;

    /**
     * @var tinyint(1) not null
     * @castTo boolean
     */
    protected $gender;

    /**
     * @var int(2) not null
     */
    protected $pref;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column last_login_date
     * @castTo datetime
     */
    protected $lastLoginDate;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column created_date
     * @castTo datetime
     */
    protected $createdDate;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column modified_date
     * @castTo datetime
     */
    protected $modifiedDate;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column deleted_date
     * @castTo datetime
     */
    protected $deletedDate;

}