<?php

/**
 * @buief
 * @details MemberHistoryEntity.
 *
 * Generated By DaoGenerator.
 * 
 * @since 2015/02/13
 * @package Onota0318
 */
namespace Core\Model;

use Onota0318\Zend2Adapter\Model\AbstractEntity;

class MemberHistoryEntity extends AbstractEntity
{
    /**
     * @var bigint(20) not null
     */
    protected $id;

    /**
     * @var bigint(20) not null
     * @column member_id
     */
    protected $memberId;

    /**
     * @var varchar(255) not null
     */
    protected $key;

    /**
     * @var varchar(255) not null
     * @column before_value
     */
    protected $beforeValue;

    /**
     * @var varchar(255) not null
     * @column after_value
     */
    protected $afterValue;

    /**
     * @var datetime not null
     * @column created_date
     * @castTo datetime
     */
    protected $createdDate;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column modified_date
     * @castTo datetime
     */
    protected $modifiedDate;

    /**
     * @var datetime 
     * @default 0000-00-00 00:00:00
     * @column deleted_date
     * @castTo datetime
     */
    protected $deletedDate;

}