<?php

/**
 * @buief
 * @details MemberAttributesTable.
 *
 * Generated By DaoGenerator.
 * 
 * @since 2015/02/13
 * @package Onota0318
 */
namespace Core\Model;
 
use Onota0318\Zend2Adapter\Model\AbstractTable;

class MemberAttributesTable extends AbstractTable
{
    const TABLE_NAME = "member_attributes";
}